openapi: "3.0.1"
info:
  title: MyGestock API
  description: API pour la gestion de stocks
  version: 1.0.0
servers:
  - url: http://localhost:8086
paths:
  /category/all:
    get:
      summary: List all category
      operationId: saveCategory
      tags:
        - category
      responses:
        '200':
          description: Voici la liste des catégorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'


components:
  schemas:
    CategoryDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string